GET http://localhost:5000/api/products?page=1&limit=9
Content-Type: application/json

###
GET http://localhost:5000/api/categories
Content-Type: application/json

###
GET http://localhost:5000/api/products?filter=Tea&page=1&limit=9
Content-Type: application/json

###
GET http://localhost:5000/api/user/profile/get
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6InhTRjRSNVMiLCJ1c2VybmFtZSI6Imh1eXRlc3QwMSIsInJvbGUiOjMsImlhdCI6MTYyNjUyOTIwMSwiZXhwIjoxNjI2NTMxMDAxfQ.uDA86fKcTJAUBxF47QMuTJymBN12n8hAS7-MdhS3WTA

###
POST http://localhost:5000/api/auth/login
Content-Type: application/json

{
    "username": "customer01",
    "password": "1234567c"
}

###
PATCH http://localhost:5000/api/user/profile/edit
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6InhTRjRSNVMiLCJ1c2VybmFtZSI6Imh1eXRlc3QwMSIsInJvbGUiOjMsImlhdCI6MTYyNjUyOTIwMSwiZXhwIjoxNjI2NTMxMDAxfQ.uDA86fKcTJAUBxF47QMuTJymBN12n8hAS7-MdhS3WTA

{
    "password": "123456789huy"
}

###
GET http://localhost:5000/api/auth/verify
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6InhTRjRSNVMiLCJ1c2VybmFtZSI6Imh1eXRlc3QwMSIsInJvbGUiOjMsImlhdCI6MTYyNjUwNzczNSwiZXhwIjoxNjI2NTA5NTM1fQ.BUFk_sl66Iv-xEDRret4y6UQ8L8vuIg3nliMx1kZC2Q


###
GET http://localhost:5000/api/wishlist/get
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjJlSHVOZlMiLCJ1c2VybmFtZSI6ImN1c3RvbWVyMDEiLCJyb2xlIjozLCJpYXQiOjE2MjY3OTkyNDYsImV4cCI6MTYyNjgwMTA0Nn0.sezgig5QknwvERWM4fXrWaeCtQQz8JlcT-v9w3ngfFc

###
POST http://localhost:5000/api/wishlist/add
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjJlSHVOZlMiLCJ1c2VybmFtZSI6ImN1c3RvbWVyMDEiLCJyb2xlIjozLCJpYXQiOjE2MjY3OTkyNDYsImV4cCI6MTYyNjgwMTA0Nn0.sezgig5QknwvERWM4fXrWaeCtQQz8JlcT-v9w3ngfFc

{
    "productId": "1d009b21-e1d0-4686-9e85-ac6a63e6f9a7"
}

###
DELETE http://localhost:5000/api/wishlist/delete?productId=1d009b21-e1d0-4686-9e85-ac6a63e6f9a7
Content-Type: application/json

Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IkVyMUUydDgiLCJ1c2VybmFtZSI6ImVtcGxveWVlMDEiLCJyb2xlIjoyLCJpYXQiOjE2MjY2ODAwNjEsImV4cCI6MTYyNjY4MTg2MX0.B900zX4XBeekFUV10RKqwt3IphP2R8Qf8PIxTAUmmnc
###
GET http://localhost:5000/api/checkout/get
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IkVyMUUydDgiLCJ1c2VybmFtZSI6ImVtcGxveWVlMDEiLCJyb2xlIjoyLCJpYXQiOjE2MjY4NjA0NjAsImV4cCI6MTYyNjg2MjI2MH0.qELnGCa9x37wOdTOszFlTgxhs1wp5xd-a7p3CND0vF0
