POST http://localhost:5000/api/auth/login
Content-Type: application/json

{
    "username": "admin_01",
    "password": "1234567a"
}

###
GET http://localhost:5000/api/verify
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJyb2xlIjoxLCJ1c2VybmFtZSI6ImFkbWluXzAxIiwicGFzc3dvcmQiOiIxMjM0NTY3YSIsImlhdCI6MTYyNDY5MzczOSwiZXhwIjoxNjI0Njk1NTM5fQ.sKBevaPR4lKT1JRJ3tgiPVn4JbrGy-iGIgt62wCIzr8