GET http://localhost:5000/api/products?page=1&limit=9
Content-Type: application/json

###
GET http://localhost:5000/api/categories
Content-Type: application/json

###
GET http://localhost:5000/api/products?filter=Tea&page=1&limit=9
Content-Type: application/json

###
GET http://localhost:5000/api/user/profile/get
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6InhTRjRSNVMiLCJ1c2VybmFtZSI6Imh1eXRlc3QwMSIsInJvbGUiOjMsImlhdCI6MTYyNjUyOTIwMSwiZXhwIjoxNjI2NTMxMDAxfQ.uDA86fKcTJAUBxF47QMuTJymBN12n8hAS7-MdhS3WTA

###
POST http://localhost:5000/api/auth/login
Content-Type: application/json

{
    "username": "customer01",
    "password": "1234567c"
}

###
PATCH http://localhost:5000/api/user/profile/edit
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6InhTRjRSNVMiLCJ1c2VybmFtZSI6Imh1eXRlc3QwMSIsInJvbGUiOjMsImlhdCI6MTYyNjUyOTIwMSwiZXhwIjoxNjI2NTMxMDAxfQ.uDA86fKcTJAUBxF47QMuTJymBN12n8hAS7-MdhS3WTA

{
    "password": "123456789huy"
}

###
GET http://localhost:5000/api/auth/verify
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6InhTRjRSNVMiLCJ1c2VybmFtZSI6Imh1eXRlc3QwMSIsInJvbGUiOjMsImlhdCI6MTYyNjUwNzczNSwiZXhwIjoxNjI2NTA5NTM1fQ.BUFk_sl66Iv-xEDRret4y6UQ8L8vuIg3nliMx1kZC2Q

###
GET http://localhost:5000/api/wishlist/get
Content-Type: application/json
Authorization: Bearer 

###
POST http://localhost:5000/api/wishlist/add
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjJlSHVOZlMiLCJ1c2VybmFtZSI6ImN1c3RvbWVyMDEiLCJyb2xlIjozLCJpYXQiOjE2MjY3MTA5NzEsImV4cCI6MTYyNjcxMjc3MX0.U5rlqT1zxruLsfxcXwDa4XMiCcEU-aP5nE5fBEHREOs

{
    "productId": "5de298df-5a13-4dbd-ad7e-94a8d892aa09"
}